name: pull_request_comment_test

on:
  issue_comment:
    types: [created, edited, deleted]
  
  pull_request_review:
    types: [submitted]
   
  pull_request_review_comment:
     types: [created, edited, deleted]

  workflow_dispatch:

jobs:
  
  pr_comment:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo commented $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  pr_review:
    if: ${{ github.event.issue.reviewed }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This PR was reviewd"

  pr_approve:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This PR was approved"
