name: pr_approve_test

on:
  pull_request_review:
    types: [submitted]
    
  workflow_dispatch:

jobs:
  pr_approve:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This PR was approved"
