name: pull_request_comment_test

on:
  issue_comment:
    types: [created, edited, deleted]

  workflow_dispatch:

jobs:
  
  pr_comment:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo commented $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
