name: pr_review_test

on:
  pull_request_review_comment:
     types: [created, edited, deleted]

  workflow_dispatch:

jobs:
  pr_review:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This PR was reviewd"
